config/routes.rb
Rails.application.routes.draw do
  root to: 'libraries#index'
  mount OkComputer::Engine, at: "/status"

  resources :terms

  resources :spreadsheets do
    member do
      post :import
    end
  end

  resources :libraries do
    collection do
      get :spreadsheet
    end

    resources :term_hours, only: :index

    resources :locations do
      member do
        get :hours
      end

      resources :term_hours, except: :index
      resources :calendars
    end
  end

  resource :feedback_form, path: "feedback", only: [:new, :create]
  get "feedback" => "feedback_forms#new"
  get 'api/v1/library/:library_id/location/:id/hours/for/:when' => 'locations#hours_v1'

  get 'sso/login' => 'authorization#login', as: :login
  get 'sso/logout' => 'authorization#logout', as: :logout

end

app/views/shared/_flashes.html.erb
<div class="flashes">
<% if [flash[:success], flash[:notice], flash[:warning], flash[:error], flash[:alert]].any? %>
    <% if flash[:success] %>
      <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        <%= flash[:success] %>
      </div>
    <% end %>
    <% if flash[:notice] %>
      <div class="alert alert-info alert-dismissible" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:warning] %>
      <div class="alert alert-warning alert-dismissible" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        <%= flash[:warning] %>
      </div>
    <% end %>
    <% if flash[:error] %>
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        <%= flash[:error] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        <%= flash[:alert] %>
      </div>
    <% end %>
<% end %>
</div>

app/views/shared/_global_alert.html.erb
<%= render 'global_alerts/alerts' if Settings.GLOBAL_ALERT %>

app/views/shared/_nav_link_list.html.erb
<!-- item_class is passed down from parent template. BS4 list items use specific classes. -->

<% additional_classes ||= '' %>

<% if current_user %>
  <li class="nav-item <%= additional_classes %>">
    <%= link_to "#{current_user.id}: Logout", logout_path(referrer: root_path), class: "nav-link" %>
  </li>
  <% if can? :manage, Spreadsheet %>
    <li class="nav-item <%= additional_classes %>">
      <%= link_to 'Export Hours', spreadsheet_libraries_url, class: "nav-link" %>
    </li>
    <li class="nav-item <%= additional_classes %>">
      <%= link_to 'Import Hours', new_spreadsheet_url, class: "nav-link" %>
    </li>
  <% end %>
<% end %>

<li class="nav-item <%= additional_classes %>">
  <%= link_to 'Feedback', feedback_path, onclick: "event.preventDefault(); document.getElementById('feedback-modal').showModal();", class: "nav-link" %>
</li>

app/views/shared/_sul_footer.html.erb
<footer>
  <section id="pre-footer" class="py-4" aria-label="Library footer">
    <div class="container">
      <div class="row row-gap-3">
        <div id="sul-footer-img" class="d-none d-md-flex d-lg-none d-xl-flex col-sm-12 col-lg-3 col-xl-3 d-flex align-items-start justify-content-lg-start justify-content-md-center">
          <a href="https://library.stanford.edu" class="prefooter-logo stacked-lg" aria-label="Stanford University Libraries"></a>
        </div>
        <section class="col-md-4 col-xl-3 primary-menu" aria-label="Main links">
          <div class="d-block d-md-none d-lg-block d-xl-none mb-3">
            <a href="https://library.stanford.edu" class="prefooter-logo" aria-label="Stanford University Libraries"></a>
          </div>
          <ul class="list-unstyled fw-semibold">
            <li>
              <a href="https://library.stanford.edu/all-locations-and-hours">All locations and hours
                <i class="bi bi-arrow-right-short"></i></a>
            </li>
            <li>
              <a href="https://library.stanford.edu/">Library website
                <i class="bi bi-arrow-right-short"></i></a>
            </li>
            <li>
              <a href="https://mylibrary.stanford.edu">My Account
                <i class="bi bi-arrow-right-short"></i></a>
            </li>
            <li>
              <%= link_to "Staff login", login_path(referrer: request.original_url) %>
            </li>
          </ul>
        </section>
        <section class="col-md-4 col-xl-3 secondary-menu" aria-labelledby="get-help-header">
          <header id="get-help-header" class="fw-semibold fs-5 mb-2">
                    Get help
          </header>
          <ul class="list-unstyled">
            <li>
              <a href="https://library.stanford.edu/contact-us">Contact us</a>
            </li>
            <li>
              <a href="https://library.stanford.edu/library-accessibility">Library accessibility</a>
            </li>
            <li>
              <a href="https://library-status.stanford.edu/">System status</a>
            </li>
            <li>
              <a href="https://library.stanford.edu/ask/email/connection-problems">Report a connection problem</a>
            </li>
          </ul>
        </section>
        <section class="col-md-4 col-xl-3 secondary-menu" aria-labelledby="search-header">
          <header id="search-header" class="fw-semibold fs-5 mb-2">
                    Search
          </header>
          <ul class="list-unstyled">
            <li>
              <a href="https://searchworks.stanford.edu/">SearchWorks Catalog</a>
                      |
              <a href="https://searchworks.stanford.edu/articles">Articles+</a>
            </li>
            <li>
              <a href="https://archives.stanford.edu/">Archival Collections at Stanford</a>
            </li>
            <li>
              <a href="https://spotlight.stanford.edu/">Spotlight Exhibits</a>
            </li>
            <li>
              <a href="https://earthworks.stanford.edu/">EarthWorks</a>
            </li>
            <li>
              <a href="https://guides.library.stanford.edu/">Guides</a>
            </li>
          </ul>
        </section>
      </div>
    </div>
  </section>
  <section id="su-footer" class="text-white bg-dark pt-4 pb-4" aria-label="Stanford University footer">
    <div class="container-lg d-flex flex-column flex-lg-row align-items-center align-md-normal" title="Common Stanford resources">
      <div class="mt-1 mb-2 align-self-lg-start">
        <a class="su-logo" href="https://www.stanford.edu">Stanford<br>
          <span class="su-logo-university">University</span></a>
      </div>
      <div class="ms-lg-5">
        <nav aria-label="Global footer menu" class="d-flex flex-row gap-4 gap-sm-0 flex-sm-column justify-content-center justify-content-lg-start align-items-start align-items-sm-center align-items-lg-start">
          <ul class="justify-content-center justify-content-lg-start fw-semibold gap-sm-2 gap-md-3 gap-lg-4 list-unstyled d-flex flex-column flex-sm-row">
            <li>
              <a href="https://www.stanford.edu">
                        Stanford Home<span class="visually-hidden">(link is external)</span>
              </a>
            </li>
            <li>
              <a href="https://visit.stanford.edu/plan/">
                        Maps &amp; Directions<span class="visually-hidden">(link is external)</span></a>
            </li>
            <li>
              <a href="https://www.stanford.edu/search/">
                        Search Stanford<span class="visually-hidden">(link is external)</span>
              </a>
            </li>
            <li>
              <a href="https://emergency.stanford.edu">
                        Emergency Info<span class="visually-hidden">(link is external)</span>
              </a>
            </li>
          </ul>
          <ul class="justify-content-center justify-content-lg-start gap-sm-2 gap-md-3 gap-lg-4 list-unstyled d-flex flex-column flex-sm-row">
            <li>
              <a href="https://www.stanford.edu/site/terms/" title="Terms of use for sites">
                        Terms of Use<span class="visually-hidden">(link is external)</span>
              </a>
            </li>
            <li>
              <a href="https://www.stanford.edu/site/privacy/" title="Privacy and cookie policy">
                        Privacy<span class="visually-hidden">(link is external)</span>
              </a>
            </li>
            <li>
              <a href="https://uit.stanford.edu/security/copyright-infringement" title="Report alleged copyright infringement">
                        Copyright<span class="visually-hidden">(link is external)</span>
              </a>
            </li>
            <li>
              <a href="https://adminguide.stanford.edu/chapter-1/subchapter-5/policy-1-5-4" title="Ownership and use of Stanford trademarks and images">
                        Trademarks<span class="visually-hidden">(link is external)</span>
              </a>
            </li>
            <li>
              <a href="https://studentservices.stanford.edu/more-resources/student-policies/non-academic/non-discrimination" title="Non-discrimination policy">
                        Non-Discrimination<span class="visually-hidden">(link is external)</span>
              </a>
            </li>
            <li>
              <a href="https://www.stanford.edu/site/accessibility" title="Report web accessibility issues">
                        Accessibility<span class="visually-hidden">(link is external)</span>
              </a>
            </li>
          </ul>
        </nav>
        <div class="text-center text-lg-start copyright">
          <span class="text-nowrap">© Stanford University.</span><span class="text-nowrap">&nbsp; Stanford, California 94305.</span>
        </div>
      </div>
    </div>
  </section>
</footer>

app/views/shared/_top_navbar.html.erb
<nav id="skip-link" role="navigation" aria-label="Skip links">
  <a
    class="visually-hidden-focusable rounded-bottom m-1 py-2 px-3"
    href="#main-container"
  >
    Skip to main content
  </a>
</nav>

<header>
  <div class="container">
    <a class="su-brand-bar__logo" href="https://www.stanford.edu">
      Stanford University
    </a>
  </div>

  <nav class="navbar navbar-expand-md bg-dark" role="navigation">
    <div class="container">
      <a
        class="mb-0 navbar-brand navbar-logo"
        href="https://library.stanford.edu"
      >
        Stanford University Libraries
      </a>

      <button
        class="navbar-toggler navbar-toggler-right"
        type="button"
        data-toggle="collapse"
        data-bs-toggle="collapse"
        data-target="#user-util-collapse"
        data-bs-target="#user-util-collapse"
        aria-controls="user-util-collapse"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="d-md-block d-none">
        <ul class="navbar-nav"><%= render 'shared/nav_link_list' %></ul>
      </div>
    </div>
  </nav>

  <div class="masthead bg-dark">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-md-8 d-flex justify-content-center justify-content-md-start">
          <h1 class="my-3"><a href="/">Library Hours</a></h1>
        </div>
      </div>

      <div
        class="navbar collapse navbar-collapse bg-dark"
        id="user-util-collapse"
      >
        <ul class="navbar-nav">
          <%= render 'shared/nav_link_list', additional_classes: 'd-md-none' %>
        </ul>
      </div>
    </div>
  </div>
</header>

<% unless current_page? feedback_path %>
  <dialog id="feedback-modal">
    <div class="modal-content">
      <div class="modal-header">
        <h2 class="modal-title fw-normal">Send Feedback</h2>

        <button
          type="button"
          class="btn-close"
          onclick="this.closest('dialog').close();"
          aria-label="Close"
        ></button>
      </div>

      <div class="bg-dark-subtle py-1 px-4 border-top">
        Reporting from
        <span class="reporting-from-field"><%= request.original_url %></span>
      </div>

      <div class="modal-body"><%= render "shared/feedback_forms/form" %></div>

      <div class="modal-footer">
        <button
          type="button"
          class="btn btn-outline-primary me-2 close"
          onclick="this.closest('dialog').close();"
        >
          Close
        </button>

        <button type="submit" form="feedback-form" class="btn btn-primary">
          Send
        </button>
      </div>
    </div>
  </dialog>
<% end %>