config/routes.rb
Rails.application.routes.draw do
  root to: 'libraries#index'
  mount OkComputer::Engine, at: "/status"

  resources :terms

  resources :spreadsheets do
    member do
      post :import
    end
  end

  resources :libraries do
    collection do
      get :spreadsheet
    end

    resources :term_hours, only: :index

    resources :locations do
      member do
        get :hours
      end

      resources :term_hours, except: :index
      resources :calendars
    end
  end

  resource :feedback_form, path: "feedback", only: [:new, :create]
  get "feedback" => "feedback_forms#new"
  get 'api/v1/library/:library_id/location/:id/hours/for/:when' => 'locations#hours_v1'

  get 'sso/login' => 'authorization#login', as: :login
  get 'sso/logout' => 'authorization#logout', as: :logout

end

app/models/library.rb
# frozen_string_literal: true

class Library < ApplicationRecord
  has_many :locations
  accepts_nested_attributes_for :locations, allow_destroy: true

  validates :name, presence: true

  extend FriendlyId

  friendly_id :slug, use: %i[slugged finders history]

  def sort_key
    return '0' if slug == Settings.pinned_library_slug

    name
  end

  def primary_location
    @primary_location ||= locations.find(&:primary)
  end
end

app/controllers/libraries_controller.rb
# frozen_string_literal: true

class LibrariesController < ApplicationController
  load_and_authorize_resource

  before_action :set_range, only: %i[show index]

  # GET /libraries
  # GET /libraries.json
  def index
    @libraries = @libraries.select { |x| x.locations.any?(&:keeps_hours) }.sort_by(&:sort_key)
    respond_to do |format|
      format.html do
        @libraries = @libraries.select(&:public) unless current_user&.site_admin? || current_user&.superadmin?
      end

      format.json
      format.csv { render plain: LegacySpreadsheetParser.generate(@libraries.select { |x| params[:ids].blank? || params[:ids].include?(x.id.to_s) }, @range) }
    end
  end

  # GET /libraries/1
  # GET /libraries/1.json
  def show
    respond_to do |format|
      format.html
      format.json
    end
  end

  def spreadsheet; end

  # GET /libraries/new
  def new; end

  # GET /libraries/1/edit
  def edit; end

  # POST /libraries
  # POST /libraries.json
  def create
    respond_to do |format|
      if @library.save
        format.html { redirect_to @library, notice: 'Library was successfully created.' }
        format.json { render :show, status: :created, location: @library }
      else
        format.html { render :new }
        format.json { render json: @library.errors, status: :unprocessable_content }
      end
    end
  end

  # PATCH/PUT /libraries/1
  # PATCH/PUT /libraries/1.json
  def update
    respond_to do |format|
      if @library.update(library_params)
        format.html { redirect_to @library, notice: 'Library was successfully updated.' }
        format.json { render :show, status: :ok, location: @library }
      else
        format.html { render :edit }
        format.json { render json: @library.errors, status: :unprocessable_content }
      end
    end
  end

  # DELETE /libraries/1
  # DELETE /libraries/1.json
  def destroy
    @library.destroy
    respond_to do |format|
      format.html { redirect_to libraries_url, notice: 'Library was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def library_params
    params.expect(library: [:name, :slug, :about_url, :public, locations_attributes: locations_params])
  end

  def locations_params
    [:id, :name, :note, :slug, :keeps_hours, :primary, :_destroy]
  end
end

app/helpers/libraries_helper.rb
# frozen_string_literal: true

module LibrariesHelper
end

app/views/libraries/_form.html.erb
<%= form_with model: @library, data: { controller: 'nested-form', nested_form_selector_value: '.inner-container' } do |form| %>
  <% if @library.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@library.errors.count, "error") %> prohibited this library from being saved:</h2>
      <ul>
      <% @library.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, "Name:", class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control'%>
  </div>

  <div class="mb-3">
    <%= form.label :about_url, class: 'form-label' %>
    <%= form.text_field :about_url, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :slug, "Slug:", class: 'form-label' %>
    <%= form.text_field :slug, class: 'form-control' %>
  </div>

  <div class="form-check">
    <%= form.check_box :public, class: "form-check-input" %>
    <%= form.label :public, "Display on home page", class: "form-check-label" %>
  </div>

  <h2 class="mt-4">Library's Locations:</h2>

  <ul class="list-unstyled" data-nested-form-target="addItem">
    <%= form.fields_for :locations do |locations_form| %>
        <li class="inner-container border-bottom border-dark-subtle my-3 py-3">
          <div class="mb-3">
            <%= locations_form.label :name, "Name:", required: true, class: 'form-label'  %>
            <%= locations_form.text_field :name, class: 'form-control'%>
          </div>
          <div class="mb-3">
            <%= locations_form.label :slug, "Slug:", required: true, class: 'form-label'  %>
            <%= locations_form.text_field :slug, class: 'form-control'%>
          </div>
          <div class="mb-3">
            <%= locations_form.label :note, "Note:", class: 'form-label'  %>
            <%= locations_form.text_field :note, class: 'form-control'%>
          </div>
          <div class="form-check">
            <%= locations_form.check_box :keeps_hours, class: "form-check-input" %>
            <%= locations_form.label :keeps_hours, "Keeps hours", class: "form-check-label" %>
          </div>
          <div class="form-check">
            <%= locations_form.check_box :primary, class: "form-check-input" %>
            <%= locations_form.label :primary, "Use location for library hours", class: "form-check-label" %>
          </div>
          <%= button_tag type: 'button', class: 'btn btn-outline-danger', aria: { label: "Remove this Location" },
                  data: { action: "click->nested-form#removeAssociation" } do %>
            Remove this Location
          <% end %>
          <%= locations_form.hidden_field :_destroy %>
        </li>
    <% end %>
  </ul>
  <template data-nested-form-target='template'>
    <%= form.fields_for :locations, Location.new, child_index: 'TEMPLATE_RECORD' do |locations_form| %>
      <li class="inner-container">
        <%= locations_form.label :name, "Name:", required: true %>
        <%= locations_form.text_field :name, class: 'form-control'%>
        <div class="form-check">
          <%= locations_form.check_box :keeps_hours, class: "form-check-input" %>
          <%= locations_form.label :keeps_hours, "Keeps hours", class: "form-check-label" %>
        </div>
        <div class="form-check">
          <%= locations_form.check_box :primary, class: "form-check-input" %>
          <%= locations_form.label :primary, "Use location for library hours", class: "form-check-label" %>
        </div>
        <%= button_tag type: 'button', class: 'btn btn-outline-danger', aria: { label: "Remove this Location" },
                data: { action: "click->nested-form#removeAssociation" } do %>
          Remove this Location
        <% end %>
        <%= locations_form.hidden_field :_destroy %>
      </li>
    <% end %>
  </template>
  <%= button_tag "Add a Location", class: 'btn btn-outline-success',
                  data: { action: 'nested-form#addAssociation' } %>

  <div class="actions mt-3">
    <%= form.submit "Create Library", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/libraries/_hours.html.erb
<% if hours.closed? %>
  <span class="closed">closed</span>
<% elsif hours.open_24h? %>
  <span class="open-24h">open 24h</span>
<% elsif hours %>
  <time itemprop="opens" datetime="<%= hours.dtstart.localtime %>"><%= render_short_time(hours.dtstart.localtime) %></time>-<time itemprop="closes" datetime="<%= hours.dtend.localtime %>"><%= render_short_time(hours.dtend.localtime) %></time>
<% else %>
  n/a
<% end %>

app/views/libraries/_location_hours.html.erb
<table class="table table-responsive weekly-hours d-none d-md-block desktop-hours">
<div class="editable-error-block"></div>
  <thead>
    <tr>
      <th class="location-name"><span class='visually-hidden'>Location</span></th>
      <% @range.to_a.each do |d| %>
        <th class="hours <%= 'holiday' if Term.holiday? d %>">
          <% if Term.holiday? d %>
            <div><small><%= Term.holidays.for_date(d).first.name %></small></div>
          <% end %>
          <%= l(d, format: :very_short) %>
        </th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% ((locations.with_hours if locations.respond_to? :with_hours) || locations).each do |l| %>
      <tr>
        <td class="location-name"><%= render 'locations/note_popover', location: l if l.note.present? %><%= l.name %></td>

        <% l.hours(@range).each do |calendars| %>
          <td class="hours <%= 'exceptions' if calendars.any?(&:persisted?) %> <%= 'holiday' if Term.holiday? calendars.first.date %>" itemprop="openingHoursSpecification" itemscope itemtype="http://schema.org/OpeningHoursSpecification">
            <span itemprop="validFrom" content="<%= l calendars.first.date %>" aria-hidden="true"></span>
            <span itemprop="validThrough" content="<%= l calendars.first.date %>" aria-hidden="true"></span>
            <% calendars.each do |d|  %>
            <span data-bs-toggle="tooltip" data-bs-placement="left" data-bs-title="<%= [d.summary, d.description].reject(&:blank?).compact.join(" / ") %>">
              <%= render 'calendars/time', calendar: d %>
            </span>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<%= render partial: 'libraries/location_hours_mobile', locals: { locations: } %>

app/views/libraries/_location_hours_mobile.html.erb
<% ((locations.with_hours if locations.respond_to? :with_hours) || locations).each do |l| %>
  <h3 class="location-name d-md-none"><%= render 'locations/note_popover', location: l if l.note.present? %><%= l.name %></h3>
  <table class="table table-responsive mobile-hours weekly-hours d-md-none">
    <div class="editable-error-block"></div>
    <thead>
      <tr>
        <% @range.to_a.each do |d| %>
          <th class="hours <%= 'holiday' if Term.holiday? d %>">
            <% if Term.holiday? d %>
              <div class="holiday-text"><small><%= Term.holidays.for_date(d).first.name %></small></div>
            <% end %>
            <%= l(d, format: :very_short) %>
          </th>
        <% end %>
      </tr>
    </thead>
    <tbody>
        <tr>
          <% l.hours(@range).each do |calendars| %>
            <td class="hours <%= 'exceptions' if calendars.any?(&:persisted?) %> <%= 'holiday' if Term.holiday? calendars.first.date %>" itemprop="openingHoursSpecification" itemscope itemtype="http://schema.org/OpeningHoursSpecification">
              <div class="d-flex justify-space-between gap-4 <%= Term.holiday?(calendars.first.date) ? 'justify-content-center' : '' %>">
                  <div>
                    <span itemprop="validFrom" content="<%= l calendars.first.date %>" aria-hidden="true"></span>
                    <span itemprop="validThrough" content="<%= l calendars.first.date %>" aria-hidden="true"></span>
                    <% calendars.each do |d|  %>
                    <span data-bs-toggle="tooltip" data-bs-placement="left" data-bs-title="<%= [d.summary, d.description].reject(&:blank?).compact.join(" / ") %>">
                      <%= render 'calendars/time', calendar: d %>
                    </span>
                  </div>
                  <% if Term.holiday? calendars.first.date %>
                    <div class="mobile-holiday fw-semibold text-truncate"><%= Term.holidays.for_date(calendars.first.date).first.name %></div>
                  <% end %>
                </div>
              <% end %>
            </td>
          <% end %>
        </tr>
    </tbody>
  </table>
<% end %>

app/views/libraries/_range.html.erb
<div class="card bg-light date-range d-flex my-3">
  <div class="card-body py-2 row gap-3 gap-lg-0">
    <div class="align-items-center col-lg-6 col-12 d-flex justify-content-lg-start justify-content-center pager gap-2">
      <%= link_to params.to_unsafe_h.merge(week: (@range.begin - 1.week + 1.day).strftime("%GW%V")) do %>
        <span class="fas fa-arrow-left" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      <% end unless @range.begin.before?(24.months.ago)%>
      <h2 class="fw-light mb-0"><%= l(@range.begin, format: :short) %> – <%= l(@range.end, format: :short) %></h2>
      <%= link_to params.to_unsafe_h.merge(week: (@range.begin + 1.week + 1.day).strftime("%GW%V")) do %>
        <span class="fas fa-arrow-right" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      <% end unless @range.end.after?(18.months.from_now) %>
    </div>

    <div class="col-lg-6 col-12">
      <form method="GET" class="form d-flex gap-1 gap-sm-0 justify-content-lg-end justify-content-center">

        <div class="date-input">
          <label for="jump-date" class="visually-hidden">Jump to:</label>
          <div class="input-group">
            <input value="<%= Time.zone.today %>" name="date" type="date" class="form-control" id="jump-date" data-href="<%= url_for(params.to_unsafe_h.merge(week: "%GW%V")) %>"/>
            <input value="Go" type="submit" class="btn btn-primary"/>

          </div>
        </div>

        <div class="d-flex" id="jump-term-group">
          <h2 class="visually-hidden">Jump to quarters &amp; holidays</h2>
          <button id="jump-term" type="button" class="btn btn-outline-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            Quarters &amp; holidays <span class="caret"></span>
          </button>
          <ul class="dropdown-menu dropdown-menu-right" role="menu">
            <% if can? :create, Term %>
              <li class="dropdown-item"><%= link_to 'Manage Terms', terms_path %></li>
            <% end %>
            <% Term.upcoming(2.years).group_by(&:year).each do |year, terms| %>
              <li class="dropdown-item">
                <h4><%= year %></h4>
              </li>
              <% terms.each do |t| %>
                <li class="dropdown-item"><%= link_to params.to_unsafe_h.merge(week: t.dtstart.strftime("%GW%V")) do %>
                  <%= t.name %>
                  <small><%= l t.dtstart.to_date, format: :short %><%= "-" + l(t.dtend.to_date, format: :short) unless t.dtstart.to_date == t.dtend.to_date %></small>
                <% end %>
                </li>
                <% end %>
              <li role="separator" class="divider"></li>
            <% end %>
          </ul>
        </div>

      </form>
    </div>

  </div>
</div>

app/views/libraries/edit.html.erb
<% title "Edit #{@library.name}" %>
<% breadcrumb @library %>

<h1>Editing Library</h1>

<%= render 'form' %>

<%= link_to 'Show', @library, class: 'su-underline' %> |
<%= link_to 'Back', libraries_path, class: 'su-underline' %>

app/views/libraries/index.html.erb
<% breadcrumb :root %>

<%= render 'range' %>
<% @libraries.each do |library| %>
  <div class="row library-row" itemscope itemtype="http://schema.org/Place">
    <div class="col-xs-12 col-lg-3">
      <h2 itemprop="name"><%= link_to_if library.about_url, library.name, library.about_url %></h2>
      <% if can?(:edit, library) %>
        <div>
          <%= link_to 'Edit', library, class: 'btn btn-outline-secondary btn-sm' %>
          <%= link_to 'Edit hours', library_term_hours_path(library), class: 'btn btn-outline-secondary btn-sm' %>
        </div>
      <% end %>
    </div>

    <div class="col-xs-12 col-lg-9">
      <%= render partial: 'location_hours', locals: { locations: library.locations } %>
    </div>
  </div>
<% end %>

<%= link_to 'New Library', new_library_path if can? :create, Library %>

app/views/libraries/new.html.erb
<% title 'New library' %>
<h1>New Library</h1>

<%= render 'form' %>

<%= link_to 'Back', libraries_path, class: 'su-underline' %>

app/views/libraries/show.html.erb
<% title @library.name %>
<% breadcrumb @library %>

<p id="notice"><%= notice %></p>


<h1><%= @library.name %> hours</h1>

<% if @library.about_url %>
  <%= link_to root_url, class: 'location-and-access' do %>
    <span class="fas fa-arrow-left" aria-hidden="true"></span>
    All library hours
  <% end %>
<% end %>

<% if can?(:edit, @library) %>
  <div class="float-end">
    <% if current_user && current_user.superadmin? %>
      <%= link_to 'Edit library', edit_library_path(@library), class: 'btn btn-outline-secondary btn-sm' %>
    <% end %>
    <%= link_to 'Edit hours', library_term_hours_path(@library), class: 'btn btn-outline-secondary btn-sm'%>
  </div>
<% end %>

<%= render 'range' %>
<%= render partial: 'location_hours', locals: { locations: @library.locations } %>

<% if current_user && current_user.superadmin? %>
  <% if @library.locations.without_hours.any? %>
  <h2>Other locations</h2>
  <ul class="list-unstyled">
    <% @library.locations.without_hours.each do |l| %>
      <li><%= link_to l.name, library_location_path(@library, l) %></li>
    <% end %>
    </ul>
  <% end %>
<% end %>

app/views/libraries/spreadsheet.html.erb
<h1>Download library spreadsheet</h1>
<% title 'Download spreadsheet' %>
<form class="form" action="<%= libraries_path(format: 'csv') %>" method="GET">
  <div class="mb-3">
    <label class="form-label" for="ids">Libraries</label>
    <%= select_tag 'ids', options_from_collection_for_select(Library.all, :id, :name), multiple: true, class: 'form-select' %>
  </div>
  <div class="mb-3">
    <label class="form-label" id="to-from">Date range: </label>
    <%= date_field_tag 'from', nil, aria: { 'labelledby': 'to-from' } %> to <%= date_field_tag 'to', nil, aria: { 'labelledby': 'to-from' } %>
  </div>
  <input value="Download" type="submit" class="btn btn-primary" />
</form>