config/routes.rb
Rails.application.routes.draw do
  root to: 'libraries#index'
  mount OkComputer::Engine, at: "/status"

  resources :terms

  resources :spreadsheets do
    member do
      post :import
    end
  end

  resources :libraries do
    collection do
      get :spreadsheet
    end

    resources :term_hours, only: :index

    resources :locations do
      member do
        get :hours
      end

      resources :term_hours, except: :index
      resources :calendars
    end
  end

  resource :feedback_form, path: "feedback", only: [:new, :create]
  get "feedback" => "feedback_forms#new"
  get 'api/v1/library/:library_id/location/:id/hours/for/:when' => 'locations#hours_v1'

  get 'sso/login' => 'authorization#login', as: :login
  get 'sso/logout' => 'authorization#logout', as: :logout

end

app/models/calendar.rb
# frozen_string_literal: true

class Calendar < ApplicationRecord
  belongs_to :location, required: true
  has_one :library, through: :location
  validates :dtstart, :dtend, presence: true

  validate :no_parse_errors

  attr_reader :dtstart_unparsed, :dtend_unparsed

  scope :in_range, (lambda do |range|
    where('dtstart BETWEEN ? AND ?', range.begin.to_time.midnight, range.end.to_time.end_of_day)
  end)

  scope :for_date, (lambda do |t|
    where('dtstart BETWEEN ? AND ?', t.to_time.midnight, t.to_time.end_of_day)
  end)

  def self.valid_range?(range)
    case range
    when 'closed', 'open 24h'
      true
    when /-/
      parse_time_range(range).is_a? Range
    end
  rescue StandardError
    false
  end

  def self.parse_time_range(combo)
    range_begin, range_end = combo.split('-').map(&:strip)
    range_begin += 'm' if range_begin =~ /[ap]$/
    range_end += 'm' if range_end =~ /[ap]$/
    Time.zone.parse(range_begin)..Time.zone.parse(range_end)
  end

  def update_hours(combo)
    case combo
    when 'closed'
      closed!
    when 'open 24h'
      open_24h!
    when /-/
      update_range(Calendar.parse_time_range(combo))
    end
  end

  def to_text
    return '' unless persisted?
    return 'closed' if closed?
    return 'open 24h' if open_24h?

    "#{ShortTime.render(dtstart.localtime)}-#{ShortTime.render(dtend.localtime)}"
  end

  def date
    dtstart.to_date
  end

  def closed!(date = nil)
    self.closed = true

    self.dtstart_unparsed = date if date.present?
    self.dtstart = dtstart.midnight if dtstart
    self.dtend = dtstart
  end

  def dtstart_unparsed=(value)
    @dtstart_unparsed = value
    self.dtstart = Time.zone.parse(value)
  rescue StandardError => e
    parse_errors << "Unable to parse dtstart #{value}: #{e}"
  end

  def dtend_unparsed=(value)
    @dtend_unparsed = value
    parsed_val = Time.zone.parse(value)

    if dtstart.present? && parsed_val < dtstart
      next_date = parsed_val.to_date + 1.day
      parsed_val = Time.zone.parse("#{next_date} #{parsed_val.strftime('%H:%M:%S')}")
    end

    self.dtend = parsed_val
  rescue StandardError => e
    parse_errors << "Unable to parse dtend #{value}: #{e}"
  end

  def parse_errors
    @parse_errors ||= []
  end

  def no_parse_errors
    return if parse_errors.blank?

    parse_errors.each do |e|
      errors.add(:parse_errors, e)
    end
  end

  def open_24h!
    self.closed = false
    self.dtstart = dtstart.midnight
    self.dtend = dtstart.end_of_day
  end

  def update_range(range)
    self.closed = false
    self.dtstart = Time.zone.parse(dtstart.strftime('%F') + range.begin.strftime('T%T'))
    self.dtend = Time.zone.parse(dtstart.strftime('%F') + range.end.strftime('T%T'))

    if dtend < dtstart
      next_date = dtstart.to_date + 1.day
      # Parse the time again, just in case daylight saving happened.
      self.dtend = Time.zone.parse(next_date.to_s + range.end.strftime('T%T'))
    end
  end

  def open?
    !closed?
  end

  def open_24h?
    dtstart == dtstart.midnight &&
      dtend >= dtstart.end_of_day - 1.minute
  end

  def already_open_from_previous_day?
    previous_day_hours&.open? && previous_day_hours.dtend >= previous_day_hours.dtstart.end_of_day - 1.minute
  end

  def still_open_on_next_day?
    next_day_hours&.open? && next_day_hours.dtstart == next_day_hours.dtstart.midnight
  end

  def self.week(str)
    start = DateTime.strptime(str.upcase, '%GW%V').to_date - 1.day

    start..(start + 6.days)
  rescue ArgumentError
    # strptime throws an ArgumentError when the date value isn't valid
    nil
  end

  private

  def previous_day_hours
    @previous_day_hours ||= Hours.new(location, (dtstart - 1.day).to_date..(dtstart - 1.day).to_date).first&.first if dtstart == dtstart.midnight
  end

  def next_day_hours
    @next_day_hours ||= Hours.new(location, (dtstart + 1.day).to_date..(dtstart + 1.day).to_date).first&.first if dtend >= dtstart.end_of_day - 1.minute
  end
end

app/controllers/calendars_controller.rb
# frozen_string_literal: true

class CalendarsController < ApplicationController
  load_and_authorize_resource :library
  load_and_authorize_resource :location, through: :library
  load_and_authorize_resource through: :location

  # This operates as the show route for the non-persisted calendar entry
  def index
    day = Time.zone.parse(params[:day]).to_date
    @calendar = @location.hours(day..day).default_for_date(day)
    render 'show'
  end

  def show; end

  def new
    @calendar.dtstart = Time.zone.parse(params[:day])
  end

  def edit; end

  def create
    @calendar.dtstart = Time.zone.parse(params[:day])

    unless Calendar.valid_range? date_params[:time]
      @calendar.errors.add(:base, :format, message: "#{date_params[:time]} is not a valid time")
      render('edit') && return
    end

    @calendar.update_hours(date_params[:time])

    return if @calendar.save

    render :new
  end

  def update
    unless Calendar.valid_range? date_params[:time]
      render(status: :bad_request, plain: "#{date_params[:time]} is not a valid time") && return
    end

    @calendar.update_hours(date_params[:time])

    return if @calendar.save

    render :edit
  end

  private

  def date_params
    params.expect(date: %i[day time])
  end
end

app/views/calendars/_form.html.erb
<% url = calendar.persisted? ? library_location_calendar_path(calendar.library, calendar.location, calendar) : library_location_calendars_path(calendar.location.library, calendar.location, day: calendar.date) %>

<%= form_with model: calendar, url: url do |f| %>
  <% if f.object.errors.any? %>
    <p class="alert alert-danger"><%= to_sentence f.object.errors.full_messages %></p>
  <% end %>
  <div class="input-group" style="width: 14em;">
    <%= text_field_tag 'date[time]', f.object.to_text, class: 'form-control', style: 'width: 8em' %>
    <%= f.hidden_field :date, name: 'day' %>
    <%= button_tag class: 'btn btn-primary' do %>
      <i class="fas fa-check"></i>
    <% end %>
    <%= link_to url, class: 'btn btn-outline-secondary' do %>
      <i class="fas fa-times"></i>
    <% end %>
  </div>
<% end%>

app/views/calendars/_time.html.erb
<% if can? :edit, calendar %>
  <%= turbo_frame_tag [calendar.location_id, calendar.date] do %>
    <% url = calendar.persisted? ? edit_library_location_calendar_path(calendar.library, calendar.location, calendar) : new_library_location_calendar_path(calendar.location.library, calendar.location, day: calendar.date) %>
    <%= link_to url, class: 'editable' do %>
      <%= render_hours(calendar) %>
    <% end %>
  <% end %>
<% else %>
  <%= render_hours(calendar) %>
<% end %>

app/views/calendars/create.html.erb
<%= render 'time', calendar: @calendar %>

app/views/calendars/edit.html.erb
<%= turbo_frame_tag [@calendar.location_id, @calendar.date] do %>
  <%= render "form", calendar: @calendar %>
<% end %>

app/views/calendars/new.html.erb
<%= turbo_frame_tag [@calendar.location_id, @calendar.date] do %>
  <%= render "form", calendar: @calendar %>
<% end %>

app/views/calendars/show.html.erb
<%= render 'time', calendar: @calendar %>

app/views/calendars/update.html.erb
<%= render 'time', calendar: @calendar %>