config/routes.rb
Rails.application.routes.draw do
  root to: 'libraries#index'
  mount OkComputer::Engine, at: "/status"

  resources :terms

  resources :spreadsheets do
    member do
      post :import
    end
  end

  resources :libraries do
    collection do
      get :spreadsheet
    end

    resources :term_hours, only: :index

    resources :locations do
      member do
        get :hours
      end

      resources :term_hours, except: :index
      resources :calendars
    end
  end

  resource :feedback_form, path: "feedback", only: [:new, :create]
  get "feedback" => "feedback_forms#new"
  get 'api/v1/library/:library_id/location/:id/hours/for/:when' => 'locations#hours_v1'

  get 'sso/login' => 'authorization#login', as: :login
  get 'sso/logout' => 'authorization#logout', as: :logout

end

app/models/spreadsheet.rb
# frozen_string_literal: true

class Spreadsheet < ApplicationRecord
  has_one_attached :attachment

  validate :attachment_validation

  delegate :bad_data, to: :parser

  def import
    parser.process!
  end

  def locations
    Hash[*parser.locations.map { |l| [l, find_location(l)] }.flatten]
  end

  def find_location(location)
    if location.include?('/')
      lib, loc = location.split('/', 2).map(&:strip)
      Library.find(lib).locations.find(loc)
    else
      Location.find(location)
    end
  rescue ActiveRecord::RecordNotFound
    nil
  end

  def continuous?
    dates.length == 1
  end

  def dates
    parser.date_ranges
  end

  def parser
    @parser ||= LegacySpreadsheetParser.new(attachment.download)
  end

  private

  def attachment_validation
    errors.add(:attachment, 'Missing attachment') unless attachment.attached?
  end
end

app/controllers/spreadsheets_controller.rb
# frozen_string_literal: true

class SpreadsheetsController < ApplicationController
  load_and_authorize_resource

  # GET /spreadsheets
  # GET /spreadsheets.json
  def index
    @spreadsheets = Spreadsheet.all
  end

  # GET /spreadsheets/1
  # GET /spreadsheets/1.json
  def show; end

  # GET /spreadsheets/new
  def new
    @spreadsheet = Spreadsheet.new
  end

  # GET /spreadsheets/1/edit
  def edit; end

  # POST /spreadsheets/1/import
  def import
    if @spreadsheet.import
      redirect_to root_url, notice: 'Spreadsheet was successfully imported.'
    else
      render :show
    end
  end

  # POST /spreadsheets
  # POST /spreadsheets.json
  def create
    @spreadsheet = Spreadsheet.new(spreadsheet_params)

    respond_to do |format|
      if @spreadsheet.save
        format.html { redirect_to @spreadsheet, notice: 'Spreadsheet was successfully created.' }
        format.json { render :show, status: :created, location: @spreadsheet }
      else
        format.html { render :new }
        format.json { render json: @spreadsheet.errors, status: :unprocessable_content }
      end
    end
  end

  # PATCH/PUT /spreadsheets/1
  # PATCH/PUT /spreadsheets/1.json
  def update
    respond_to do |format|
      if @spreadsheet.update(spreadsheet_params)
        format.html { redirect_to @spreadsheet, notice: 'Spreadsheet was successfully updated.' }
        format.json { render :show, status: :ok, location: @spreadsheet }
      else
        format.html { render :edit }
        format.json { render json: @spreadsheet.errors, status: :unprocessable_content }
      end
    end
  end

  # DELETE /spreadsheets/1
  # DELETE /spreadsheets/1.json
  def destroy
    @spreadsheet.destroy
    respond_to do |format|
      format.html { redirect_to spreadsheets_url, notice: 'Spreadsheet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def spreadsheet_params
    params.expect(spreadsheet: [:attachment])
  end
end

app/helpers/spreadsheets_helper.rb
# frozen_string_literal: true

module SpreadsheetsHelper
end

app/views/spreadsheets/_form.html.erb
<%= form_for(@spreadsheet, class: 'form-horizontal') do |f| %>
  <% if @spreadsheet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@spreadsheet.errors.count, "error") %> prohibited this spreadsheet from being saved:</h2>

      <ul>
      <% @spreadsheet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= f.label :attachment, class: 'form-label' %>
    <%= f.file_field :attachment, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit 'Upload', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/spreadsheets/edit.html.erb
<h1>Editing Spreadsheet</h1>

<%= render 'form' %>

<%= link_to 'Show', @spreadsheet, class: 'su-underline' %> |
<%= link_to 'Back', spreadsheets_path, class: 'su-underline' %>

app/views/spreadsheets/index.html.erb
<h1>Listing Spreadsheets</h1>

<table>
  <thead>
    <tr>
      <th>Attachment</th>
      <th>Attachment filename</th>
      <th>Attachment content type</th>
      <th>Attachment size</th>
      <th>Status</th>
      <th>Show link</th>
      <th>Edit link</th>
      <th>Destroy link</th>
    </tr>
  </thead>

  <tbody>
    <% @spreadsheets.each do |spreadsheet| %>
      <tr>
        <td><%= spreadsheet.attachment_id %></td>
        <td><%= spreadsheet.attachment_filename %></td>
        <td><%= spreadsheet.attachment_content_type %></td>
        <td><%= spreadsheet.attachment_size %></td>
        <td><%= spreadsheet.status %></td>
        <td><%= link_to 'Show', spreadsheet %></td>
        <td><%= link_to 'Edit', edit_spreadsheet_path(spreadsheet) %></td>
        <td><%= link_to 'Destroy', spreadsheet, data: { turbo_confirm: 'Are you sure?', turbo_method: 'delete' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Spreadsheet', new_spreadsheet_path %>

app/views/spreadsheets/new.html.erb
<h1>New Spreadsheet</h1>

<p>This form lets you upload a CSV (Comma-Separated-Value) file from your local computer that contains information about library hours. The file should have been created using the Export CSV command in this application and then edited by staff responsible for providing hours information for a particular library. Once you upload the file, you'll see a screen that will let you run some general tests to make sure the file is in the proper format. If the file passes the tests, you'll then be able to save the information in the hours database.</p>

<p>Click on the "Choose File" button to choose the file, then click "Upload" to upload it.</p>

<%= render 'form' %>

<%= link_to 'Back', spreadsheets_path, class: 'su-underline' %>

app/views/spreadsheets/show.html.erb
<h1>Validate Spreadsheet</h1>

<p>
  <strong>Attachment:</strong>
  <%= link_to @spreadsheet.attachment_filename, @spreadsheet.attachment_id %> (<%= @spreadsheet.attachment_content_type %>; <%= number_to_human_size @spreadsheet.attachment_size %>)
</p>

<p>
  <strong>Locations:</strong>
  <ul class="list-unstyled compact-alerts">
    <% @spreadsheet.locations.each do |slug, l| %>
      <% if l %>
        <li class="alert alert-success"><%= slug %> : <%= link_to l.library.name, l.library %> / <%= link_to l.name, [l.library, l] %></li>
      <% else %>
        <li class="alert alert-danger"><%= slug %> : unable to find library</li>
      <% end %>
    <% end %>
  </ul>
</p>

<p>
  <strong>Dates range:</strong>

  <ul class="list-unstyled alert <%= @spreadsheet.continuous? ? 'alert-success' : 'alert-danger' %>">
    <% @spreadsheet.dates.each do |range| %>
      <li>From <%= range.begin %> through <%= range.end %></li>
    <% end %>
  </ul>
</p>

<p>
  <strong>Bad or missing data:</strong>
    <% c = @spreadsheet.bad_data.reject { |cal| cal.location.blank? } %>
    <ul class="list-unstyled alert <%= c.none? ? 'alert-success' : 'alert-danger' %>">
      <% c.each do |cal| %>
        <li><%= cal.dtstart_unparsed %>: <%= "#{cal.library.try(:slug)} / #{cal.location.try(:slug)}" %> <%= cal.errors.messages %></li>
      <% end %>
    </ul>
</p>

<%= link_to 'Import', import_spreadsheet_path(@spreadsheet), data: { turbo_method: "post" }, class: 'btn btn-primary' %>